name: GitHub Pages deploy

on:
  push:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Install Yarn
      run: npm i -g yarn
    - name: Install dependencies
      run: yarn
    - name: Generate
      run: yarn build
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}